//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VF_API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FailureModelValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FailureModelValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VF_API.Resources.FailureModelValidationMessages", typeof(FailureModelValidationMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeord matcher ikke hinanden.
        /// </summary>
        public static string ConfirmedPasswordNotMatchForPassword {
            get {
                return ResourceManager.GetString("ConfirmedPasswordNotMatchForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid confirmed password.
        /// </summary>
        public static string InvalidConfirmedPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email er ikke gyldig.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeord er ikke gyldigt.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token could not be null or empty.
        /// </summary>
        public static string NullEmptyAccessToken {
            get {
                return ResourceManager.GetString("NullEmptyAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id can not be null or empty.
        /// </summary>
        public static string NullEmptyCategoryId {
            get {
                return ResourceManager.GetString("NullEmptyCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name can not be null or empty.
        /// </summary>
        public static string NullEmptyCategoryName {
            get {
                return ResourceManager.GetString("NullEmptyCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed password could not be null or empty.
        /// </summary>
        public static string NullEmptyConfirmedPassword {
            get {
                return ResourceManager.GetString("NullEmptyConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email shoud not be null or empty.
        /// </summary>
        public static string NullEmptyEmail {
            get {
                return ResourceManager.GetString("NullEmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password could not be null or empty.
        /// </summary>
        public static string NullEmptyPassword {
            get {
                return ResourceManager.GetString("NullEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product barcode can not be null or empty.
        /// </summary>
        public static string NullEmptyProductBarcode {
            get {
                return ResourceManager.GetString("NullEmptyProductBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description can not be null or empty.
        /// </summary>
        public static string NullEmptyProductDescription {
            get {
                return ResourceManager.GetString("NullEmptyProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product image can not be null or empty.
        /// </summary>
        public static string NullEmptyProductImageUrl {
            get {
                return ResourceManager.GetString("NullEmptyProductImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name can not be null or empty.
        /// </summary>
        public static string NullEmptyProductName {
            get {
                return ResourceManager.GetString("NullEmptyProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider could not be null or empty.
        /// </summary>
        public static string NullEmptyProvider {
            get {
                return ResourceManager.GetString("NullEmptyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating can not be null.
        /// </summary>
        public static string NullEmptyRating {
            get {
                return ResourceManager.GetString("NullEmptyRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review content can not null.
        /// </summary>
        public static string NullEmptyReviewContent {
            get {
                return ResourceManager.GetString("NullEmptyReviewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product must be have sub category.
        /// </summary>
        public static string NullEmptySubCategoryId {
            get {
                return ResourceManager.GetString("NullEmptySubCategoryId", resourceCulture);
            }
        }
    }
}
